[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "dash>=3.3.0",
    "fastapi>=0.124.2",
    "flask>=3.1.2",
    "plotly>=6.5.0",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
